import { useEffect, useState } from 'react';
import DashboardShell from '../layouts/DashboardShell.jsx';
import './ParticipantDashboard.css';
import './JudgeEnhancements.css';

export const EVALUATION_CRITERIA = [
  { key: 'completeness', name: 'Completeness', maximum: 20 }, { key: 'technical_execution', name: 'Technical Execution', maximum: 20 },
  { key: 'innovation_creativity', name: 'Innovation & Creativity', maximum: 15 }, { key: 'applicability_scalability', name: 'Applicability & Scalability', maximum: 15 },
  { key: 'ui_ux', name: 'UI/UX', maximum: 10 }, { key: 'bonus_features', name: 'Bonus Features', maximum: 10 },
  { key: 'presentation', name: 'Presentation', maximum: 5 }, { key: 'work_distribution', name: 'Work Distribution', maximum: 5 },
];
const emptyScores = Object.fromEntries(EVALUATION_CRITERIA.map(({ key }) => [key, 0]));
const roundNames = { round_1: 'Round 1', round_2: 'Round 2', round_3: 'Round 3' };

function Evaluation({ team, round, apiBase, reload, notify }) {
  const saved = team.evaluations?.find((item) => item.roundIdentifier === round);
  const [scores, setScores] = useState({ ...emptyScores, ...saved });
  const [comments, setComments] = useState(saved?.comments || '');
  const [saving, setSaving] = useState(false);
  const total = EVALUATION_CRITERIA.reduce((sum, item) => sum + Number(scores[item.key] || 0), 0);
  const change = (key, amount) => { const maximum = EVALUATION_CRITERIA.find((item) => item.key === key).maximum; setScores((current) => ({ ...current, [key]: Math.max(0, Math.min(maximum, Number(current[key]) + amount)) })); };
  async function save(event) { event.preventDefault(); setSaving(true); try { const response = await fetch(`${apiBase}/api/judge/round-evaluations/${round}/${team.team_id}`, { method: 'POST', credentials: 'include', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ ...scores, comments }) }); const body = await response.json().catch(() => ({})); if (!response.ok) throw new Error(body?.error?.message || 'Unable to save evaluation.'); notify(`${roundNames[round]} evaluation saved.`); await reload(); } catch (error) { notify(error.message, 'error'); } setSaving(false); }
  return <form className="judge-presentation-evaluation" onSubmit={save}><div className="judge-score-list">{EVALUATION_CRITERIA.map(({ key, name, maximum }) => <div className="judge-score-row" key={key}><span className="judge-score-name"><strong>{name}</strong><small>/ {maximum}</small></span><div className="judge-score-controls"><button type="button" className="judge-score-btn" onClick={() => change(key, -1)} aria-label={`Decrease ${name}`}>-</button><span className="judge-score-value">{scores[key]}</span><button type="button" className="judge-score-btn" onClick={() => change(key, 1)} aria-label={`Increase ${name}`}>+</button></div></div>)}</div><label className="dash-field"><span>Feedback</span><textarea value={comments} onChange={(event) => setComments(event.target.value)} rows={2} /></label><div className="judge-score-submit"><button className="btn btn--secondary" disabled={saving}>{saving ? 'Saving...' : saved ? 'Update Evaluation' : 'Save Evaluation'}</button><span>Total: <strong>{total} / 100</strong></span></div></form>;
}

function JudgeDashboard() {
  const apiBase = import.meta.env.VITE_API_URL || 'http://localhost:3000';
  const [activeTab, setActiveTab] = useState('overview'); const [teams, setTeams] = useState([]); const [loading, setLoading] = useState(true); const [error, setError] = useState(''); const [message, setMessage] = useState({ text: '', type: '' }); const [downloading, setDownloading] = useState(null);
  async function reload() { setLoading(true); setError(''); try { const response = await fetch(`${apiBase}/api/judge/round-evaluations`, { credentials: 'include' }); const body = await response.json().catch(() => ({})); if (!response.ok) throw new Error(body?.error?.message || 'Unable to load evaluations.'); setTeams(body.teams || []); } catch (loadError) { setError(loadError.message); } setLoading(false); }
  useEffect(() => { reload(); }, []);
  const notify = (text, type = 'success') => { setMessage({ text, type }); setTimeout(() => setMessage({ text: '', type: '' }), 4000); };
  async function download(team) { setDownloading(team.team_id); try { const response = await fetch(`${apiBase}/api/judge/teams/${team.team_id}/presentation`, { credentials: 'include' }); if (!response.ok) throw new Error('Unable to download presentation.'); const url = URL.createObjectURL(await response.blob()); const link = document.createElement('a'); link.href = url; link.download = team.original_filename; document.body.appendChild(link); link.click(); link.remove(); URL.revokeObjectURL(url); } catch (downloadError) { notify(downloadError.message, 'error'); } setDownloading(null); }
  function content(round) { return <div className="dash-section"><h2 className="dash-title">{roundNames[round]}</h2>{teams.length === 0 ? <div className="dash-empty glass-card"><p>No teams are registered yet.</p></div> : <div className="dash-table-wrap glass-card"><table className="dash-table"><thead><tr><th>Team</th><th>{round === 'round_1' ? 'Presentation' : round === 'round_2' ? 'Project submission' : 'Scoring'}</th><th>Evaluation</th></tr></thead><tbody>{teams.map((team) => <tr key={team.team_id}><td><strong>{team.team_name}</strong><br /><small>{team.leader_name}</small></td><td>{round === 'round_1' ? team.original_filename ? <button type="button" className="btn btn--secondary" onClick={() => download(team)} disabled={downloading === team.team_id}>{downloading === team.team_id ? 'Downloading...' : 'Download PPT'}</button> : 'Not provided' : round === 'round_2' ? <><strong>{team.title || 'Untitled project'}</strong>{team.description && <p>{team.description}</p>}{team.tech_stack && <p><small>Tech: {team.tech_stack}</small></p>}{team.repository_url ? <p><a href={team.repository_url} target="_blank" rel="noopener noreferrer">Open GitHub repository</a></p> : <p>GitHub: Not provided</p>}{team.deployed_url ? <p><a href={team.deployed_url} target="_blank" rel="noopener noreferrer">Open demo server</a></p> : <p>Demo: Not provided</p>}<small>Status: {team.submission_status || 'not submitted'}{team.submitted_at ? ` · Submitted ${new Date(team.submitted_at).toLocaleString()}` : ''}</small></> : 'All eight criteria'}</td><td><Evaluation team={team} round={round} apiBase={apiBase} reload={reload} notify={notify} /></td></tr>)}</tbody></table></div>}</div>; }
  const evaluated = teams.filter((team) => team.evaluations?.length).length;
  return <DashboardShell role="judge" roleLabel="Judge" activeTab={activeTab} onTabChange={setActiveTab}>{message.text && <div className={`dash-message dash-message--${message.type}`}>{message.text}</div>}{loading ? <div className="dash-loading"><div className="spinner" /></div> : error ? <div className="dash-notice glass-card"><h2>Unable to load judge data</h2><p>{error}</p><button className="btn btn--secondary" onClick={reload}>Try again</button></div> : activeTab === 'overview' ? <div className="dash-section"><div className="dash-welcome glass-card"><h1>Judge Panel</h1><p>Evaluate every team across all three rounds.</p></div><div className="dash-stats-grid"><div className="dash-stat-card glass-card"><span className="dash-stat-value">{teams.length}</span><span className="dash-stat-label">Teams</span></div><div className="dash-stat-card glass-card"><span className="dash-stat-value">{evaluated}</span><span className="dash-stat-label">Evaluated Teams</span></div></div></div> : content(activeTab)}</DashboardShell>;
}
export default JudgeDashboard;
